# Auto-generated from cog command decorators for the website.
COMMAND_GROUPS = [{'slug': 'automation',
  'label': 'Otomasyon',
  'commands': [{'name': 'notifications',
                'description': 'Otomatik V-Tracker bildirimlerini yönetir.',
                'aliases': ['bildirimler']}]},
 {'slug': 'community',
  'label': 'Topluluk',
  'commands': [{'name': 'rival', 'description': 'Bir kullanıcıyı kalıcı rival olarak seçer.', 'aliases': ['rakip']},
               {'name': 'rivalstats',
                'description': 'Rivalınla güncel karşılaştırma yapar.',
                'aliases': ['rakipstats']},
               {'name': 'duo', 'description': 'İki oyuncunun duo uyumunu hesaplar.', 'aliases': ['duoscore', 'uyum']},
               {'name': 'lfg',
                'description': 'Takım arkadaşı arama ilanı oluşturur.',
                'aliases': ['takimbul', 'takım bul']},
               {'name': 'lfgclose', 'description': 'Aktif LFG ilanını kapatır.', 'aliases': ['lfgkapat']},
               {'name': 'friendcard',
                'description': 'İki oyuncu için ortak performans kartı oluşturur.',
                'aliases': ['arkadas', 'arkadaş']}]},
 {'slug': 'economy',
  'label': 'Ekonomi',
  'commands': [{'name': 'balance', 'description': 'V-Coin bakiyeni gösterir.', 'aliases': ['bakiye', 'bal', 'para']},
               {'name': 'daily', 'description': '24 saatte bir V-Coin alırsın.', 'aliases': ['gunluk', 'günlük']},
               {'name': 'weekly',
                'description': '7 günde bir haftalık V-Coin alırsın.',
                'aliases': ['haftalik', 'haftalık']},
               {'name': 'transfer',
                'description': 'Kayıtlı bir kullanıcıya V-Coin gönderir.',
                'aliases': ['gonder', 'gönder', 'give']},
               {'name': 'leaderboard',
                'description': 'V-Coin sıralamasını gösterir.',
                'aliases': ['lb', 'top', 'zenginler']},
               {'name': 'shop',
                'description': 'Profil özelleştirme mağazasını gösterir.',
                'aliases': ['magaza', 'mağaza']},
               {'name': 'buy', 'description': 'Profil özelliğinin kilidini açar.', 'aliases': ['satinal', 'satınal']},
               {'name': 'customize',
                'description': 'Satın alınan profil görünümünü ayarlar.',
                'aliases': ['profil_ayarla']},
               {'name': 'challenges',
                'description': 'Günlük ve haftalık görev önerilerini gösterir.',
                'aliases': ['gorevler', 'görevler']}]},
 {'slug': 'core',
  'label': 'Genel',
  'commands': [{'name': 'help',
                'description': 'V-Tracker özellik ve komut merkezini gösterir.',
                'aliases': ['yardim', 'yardım']}]},
 {'slug': 'moderation',
  'label': 'Moderasyon',
  'commands': [{'name': 'clear', 'description': 'Mesaj temizler.', 'aliases': ['sil', 'purge']},
               {'name': 'warn', 'description': 'Kullanıcıya uyarı kaydı ekler.', 'aliases': ['uyar']},
               {'name': 'warnings',
                'description': 'Kullanıcının son uyarılarını listeler.',
                'aliases': ['uyarilar', 'uyarılar']},
               {'name': 'timeout', 'description': 'Kullanıcıya geçici timeout uygular.', 'aliases': ['mute']},
               {'name': 'untimeout',
                'description': 'Kullanıcının aktif timeout cezasını kaldırır.',
                'aliases': ['unmute']},
               {'name': 'kick', 'description': 'Kullanıcıyı sunucudan atar.', 'aliases': []},
               {'name': 'ban', 'description': 'Kullanıcıyı yasaklar.', 'aliases': []},
               {'name': 'lockdown', 'description': 'Bulunduğun kanalı yazmaya kapatır.', 'aliases': ['kilit']},
               {'name': 'unlock', 'description': 'Kanal yazma kilidini kaldırır.', 'aliases': []},
               {'name': 'auditlog', 'description': 'Son moderasyon işlemlerini gösterir.', 'aliases': ['modlog']}]},
 {'slug': 'security',
  'label': 'Güvenlik',
  'commands': [{'name': 'risk',
                'description': 'Bir kullanıcının son güvenlik risk olaylarını özetler.',
                'aliases': ['riskscore']},
               {'name': 'quarantine', 'description': 'Kullanıcıyı karantina rolüne alır.', 'aliases': ['karantina']},
               {'name': 'unquarantine', 'description': 'Karantina rolünü kaldırır.', 'aliases': ['karantinacikar']},
               {'name': 'modpanel',
                'description': 'Sunucunun V-Tracker güvenlik özetini gösterir.',
                'aliases': ['securitypanel']}]},
 {'slug': 'account',
  'label': 'Hesap',
  'commands': [{'name': 'register',
                'description': 'Riot hesabın için manuel sahiplik doğrulama talebi oluşturur.',
                'aliases': ['kayit', 'kayıt']},
               {'name': 'verification',
                'description': 'Hesap doğrulama durumunu gösterir.',
                'aliases': ['dogrulama', 'doğrulama']},
               {'name': 'verify',
                'description': 'Bekleyen Riot hesap doğrulama talebini yetkili olarak onaylar.',
                'aliases': []},
               {'name': 'rejectverify',
                'description': 'Bekleyen Riot hesap doğrulama talebini yetkili olarak reddeder.',
                'aliases': []},
               {'name': 'sync',
                'description': 'Doğrulanmış hesabın Riot ID değiştiyse aynı PUUID üzerinden günceller.',
                'aliases': ['senkronize']}]},
 {'slug': 'reports',
  'label': 'Raporlar',
  'commands': [{'name': 'dailyreport',
                'description': 'Güncel oyuncu gün raporunu oluşturur.',
                'aliases': ['gunlukrapor', 'günlükrapor']},
               {'name': 'weeklyreport',
                'description': 'Son 7 günlük kayıtlı performans trendini gösterir.',
                'aliases': ['haftalikrapor', 'haftalıkrapor']},
               {'name': 'weeklytop',
                'description': 'Sunucudaki haftalık gelişim liderlerini gösterir.',
                'aliases': ['haftaliktop', 'haftalıktop']},
               {'name': 'streak',
                'description': 'Son maç kazanma/kaybetme serisini gösterir.',
                'aliases': ['seri', 'formseri']}]},
 {'slug': 'server',
  'label': 'Sunucu',
  'commands': [{'name': 'suggest', 'description': 'Bot/sunucu önerisi gönderir.', 'aliases': ['oneri', 'öneri']},
               {'name': 'join', 'description': 'Bulunduğun ses kanalına katılır.', 'aliases': ['gel']},
               {'name': 'leave', 'description': 'Ses kanalından ayrılır.', 'aliases': ['cik', 'çık', 'git']},
               {'name': 'status', 'description': 'Bot sistem durumunu gösterir.', 'aliases': ['durum']},
               {'name': 'setup', 'description': 'Temel V-Tracker sunucu kanallarını/rollerini kurar.', 'aliases': []}]},
 {'slug': 'player',
  'label': 'Oyuncu',
  'commands': [{'name': 'stats',
                'description': 'Detaylı V-Tracker oyuncu panelini gösterir.',
                'aliases': ['profil', 'istatistik', 'profile', 'hub']},
               {'name': 'coach',
                'description': 'Oyuncuya özel, tekrarsız çalışma önerisi üretir.',
                'aliases': ['koc', 'koç', 'analiz']},
               {'name': 'playerdna',
                'description': 'Oyuncunun oyun tarzı DNA profilini çıkarır.',
                'aliases': ['dna', 'oyuncudna']},
               {'name': 'intelligence',
                'description': 'Ajan ve harita eğilimlerini yorumlar.',
                'aliases': ['zeka', 'zekâ', 'mapintel']},
               {'name': 'lastmatch',
                'description': 'Son maçı detaylı kart olarak gösterir.',
                'aliases': ['sonmac', 'sonmaç']},
               {'name': 'records', 'description': 'Kişisel rekorlarını gösterir.', 'aliases': ['rekor', 'rekorlar']},
               {'name': 'trend',
                'description': 'Kaydedilmiş performans snapshot geçmişini ve gelişim eğilimini gösterir.',
                'aliases': ['gelisim', 'gelişim']},
               {'name': 'compare',
                'description': 'İki kayıtlı oyuncuyu karşılaştırır.',
                'aliases': ['karsilastir', 'kıyasla']}]},
 {'slug': 'tactical',
  'label': 'Taktik',
  'commands': [{'name': 'agents', 'description': 'Ajan rolü ve kısa taktik rehberi.', 'aliases': ['ajan', 'ajanlar']},
               {'name': 'comp',
                'description': 'Harita için örnek takım kompozisyonu.',
                'aliases': ['kadro', 'kompozisyon']},
               {'name': 'counterstrat',
                'description': 'Rakip oyun tarzına karşı değişken strateji üretir.',
                'aliases': ['counter', 'strat']}]}]

COMMAND_COUNT = sum(len(group["commands"]) for group in COMMAND_GROUPS)
